version: "2"
services:
  skiabuild:
    build:
      context: .
      dockerfile: devenv.Dockerfile
    volumes:
      - /home/${CURRENT_USER}:/home/${CURRENT_USER}
      - ./entrypoint.sh:/entrypoint.sh
      - ./userentry.sh:/userentry.sh
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
      - /tmp:/tmp
    environment:
      - DISPLAY
      - CURRENT_UID
      - CURRENT_GID
      - CURRENT_USER
      - CURRENT_DIR
      - DISTCC_HOSTS
      - TERM=xterm-256color
    hostname: skiabuild
    stdin_open: true
    tty: true
    privileged: true
    entrypoint: /entrypoint.sh
    working_dir: /work

  skiabuild_ci:
    build:
      context: .
      dockerfile: Dockerfile
    image: jameswalmsley/skiabuild:latest
    volumes:
      - /home/${CURRENT_USER}:/home/${CURRENT_USER}

  skiatest_archlinux:
    build:
      context: .
      dockerfile: skiatest-archlinux.Dockerfile
    image: jameswalmsley/skiatest:archlinux
    volumes:
      - /home/${CURRENT_USER}:/home/${CURRENT_USER}
      - ./entrypoint.sh:/entrypoint.sh
      - ./userentry.sh:/userentry.sh
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
      - /tmp:/tmp
    environment:
      - DISPLAY
      - CURRENT_UID
      - CURRENT_GID
      - CURRENT_USER
      - CURRENT_DIR
      - TERM=xterm-256color
    hostname: skiatest
    stdin_open: true
    tty: true
    privileged: true
    entrypoint: /entrypoint.sh
    working_dir: /work

  skiatest_debian:
    build:
      context: .
      dockerfile: skiatest-debian.Dockerfile
    image: jameswalmsley/skiatest:debian
    volumes:
      - /home/${CURRENT_USER}:/home/${CURRENT_USER}
      - ./entrypoint.sh:/entrypoint.sh
      - ./userentry.sh:/userentry.sh
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
      - /tmp:/tmp
    environment:
      - DISPLAY
      - CURRENT_UID
      - CURRENT_GID
      - CURRENT_USER
      - CURRENT_DIR
      - TERM=xterm-256color
    hostname: skiatest
    stdin_open: true
    tty: true
    privileged: true
    entrypoint: /entrypoint.sh
    working_dir: /work

  skiatest_alpine:
    build:
      context: .
      dockerfile: skiatest-alpine.Dockerfile
    image: jameswalmsley/skiatest:alpine
    volumes:
      - /home/${CURRENT_USER}:/home/${CURRENT_USER}
      - ./entrypoint.sh:/entrypoint.sh
      - ./userentry.sh:/userentry.sh
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
      - /tmp:/tmp
    environment:
      - DISPLAY
      - CURRENT_UID
      - CURRENT_GID
      - CURRENT_USER
      - CURRENT_DIR
      - TERM=xterm-256color
    hostname: skiatest
    stdin_open: true
    tty: true
    privileged: true
    entrypoint: /entrypoint.sh
    working_dir: /work
